import "./globals.css";

export const metadata = {
  title: "SoloNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="p-8 h-screen">{children}</body>
    </html>
  );
}
