import AuthProvider from "@/components/AuthProvider";
import "./globals.css";

export const metadata = {
  title: "SoloNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body className="box-border text-darkgray bg-white h-screen">
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
